# Generated by Django 4.0.4 on 2022-05-15 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('header', '0007_alter_headerpagecarouse_ppp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='headerpagecarouse',
            name='ppp',
        ),
        migrations.RemoveField(
            model_name='headerpagecarouse',
            name='sub_title',
        ),
        migrations.AddField(
            model_name='headerpagecarouse',
            name='external_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='headerpagecarouse',
            name='internal_url',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='headerpagecarouse',
            name='title',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
