# Generated by Django 4.0.4 on 2022-05-15 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('header', '0008_remove_headerpagecarouse_ppp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headerpagecarouse',
            name='internal_url',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
