# Generated by Django 4.0.4 on 2022-05-14 12:10

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('footer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='footerpage',
            name='content',
            field=wagtail.core.fields.StreamField([('footer', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(required=True)), ('footers', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('txt', wagtail.core.blocks.CharBlock(required=True)), ('page', wagtail.core.blocks.PageChooserBlock(required=True)), ('url', wagtail.core.blocks.URLBlock(help_text='External URL', required=False))])))]))], blank=True, null=True),
        ),
    ]
