# Generated by Django 4.0.4 on 2022-05-15 08:15

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('footer', '0002_footerpage_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footerpage',
            name='content',
            field=wagtail.core.fields.StreamField([('footer', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.CharBlock(label='Text', max_length=50)), ('page', wagtail.core.blocks.PageChooserBlock(required=False)), ('page_url', wagtail.core.blocks.URLBlock(help_text='External URL', required=False))]))], blank=True, null=True),
        ),
    ]
