# Generated by Django 4.0.4 on 2022-05-15 12:32

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('footer', '0003_alter_footerpage_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footerpage',
            name='content',
            field=wagtail.core.fields.StreamField([('footer', wagtail.core.blocks.StructBlock([('cards', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.CharBlock(required=True)), ('page', wagtail.core.blocks.PageChooserBlock(max_length=40, required=False)), ('page_url', wagtail.core.blocks.URLBlock(max_length=60, required=False))])))]))], blank=True, null=True),
        ),
    ]
